# Generated by Django 5.2.7 on 2025-10-31 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('publication_date', models.DateField()),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('article_unique_id', models.CharField(blank=True, max_length=64, null=True)),
                ('sentiment', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('local_or_international', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'news_articles',
            },
        ),
        migrations.CreateModel(
            name='OverallAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('overall_sentiment', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Overall Analyses',
                'db_table': 'overall_analysis',
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_tags', to='datainjector.newsarticle')),
            ],
            options={
                'db_table': 'article_tags',
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='overall_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='datainjector.overallanalysis'),
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('manual_sentiment', models.CharField(blank=True, max_length=50, null=True)),
                ('manual_tags', models.JSONField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='datainjector.newsarticle')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification',
            },
        ),
    ]
