# Generated by Django 5.2.7 on 2025-11-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainjector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletag',
            name='individual_sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
